### ISSUE TITLE
Inox fails to build because of sbt-tut

### ISSUE THREAD

**Issue by romac** [epfl-lara/inox#101]
On latest `master` (3c23a864154e0eb968ce77e4c25437b1b230356a), running `sbt clean compile` yields the following error:

> [info] [tut] compiling: /Users/romac/Code/@epfl-lara/inox/src/main/doc/tutorial.md
> [error] Exception in thread "main" scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving <refinement of inox.ast.SimpleSym

**Comment by romac** [comment]
I get a similar error in `interpolations.md` when disabling tut on `tutorial.md`.

**Comment by samarion** [comment]
This is due to Scala 2.12 compiler bugs. I've massaged the documentation a bit to remove the errors, will push sometime this week.

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/inox/commit/2d898055d75f4dc590c040cfc2a402854d633960
