### ISSUE TITLE
cons instead of list in the tutorial?

### ISSUE THREAD

**Issue by MikaelMayer** [epfl-lara/inox#11]
Hello,
Is this an issue? In the [tutorial](https://github.com/epfl-lara/inox/blob/master/src/doc/tutorial.md), you say for the size funciton

```scala
if_ (ls.isInstOf(T(list)(tp))) {
  ... /* `1 + size(ls.tail)` */
} else_ {
  ... /* 0 */
}
```
But instead of list, shouldn't it be cons?
Especially in the remaining, there is no more reference to the consConstructor or cons anymore.

```scala
/* The `E(BigInt(i))` calls correspond to `IntegerLiteral(i)` ASTs. */
if_ (ls.isInstOf(T(list)(tp))) {
  /* The recursive call to `size` written `E(size)(tp)(...)` corresponds to
   * the AST `FunctionInvocation(size, Seq(tp), Seq(...))`.
   * Note that we refer to the symbol `tail` of the `consConstructor`'s second
   * field when building the selector AST. */
  E(BigInt(1)) + E(size)(tp)(ls.asInstOf(T(list)(tp)).getField(tail))
} else_ {
  E(BigInt(0))
}
```

If this is perfectly valid, can you explain me why and maybe I will update the tutorial to reflect that.

**Comment by samarion** [comment]
Ah that should indeed be a `cons` instead of `list` (both times, also in the `asInstOf` call).
