### ISSUE TITLE
RecursiveEvaluator is wrong for Application

### ISSUE THREAD

**Issue by MikaelMayer** [epfl-lara/inox#17]
Test case:

    import inox._
    import inox.trees._
    import inox.trees.dsl._
    import inox.evaluators.EvaluationResults

    val ap = ValDef(FreshIdentifier("a"), StringType, Set())
    val bp = ValDef(FreshIdentifier("b"), StringType, Set())

    val body = 
      Application(
        Application(
        Lambda(Seq(ap),
          Lambda(Seq(bp),
            StringConcat(StringConcat(ap.toVariable, StringLiteral(":")), bp.toVariable)
          )
        ), Seq(StringLiteral("Winner"))), Seq(StringLiteral("Mikael")))

    val main = FreshIdentifier("main")
    val funDef = mkFunDef(main)()(_ => (Seq(), StringType, _ => body))

    val prog = InoxProgram(
      Context.empty,
      funDef::Nil, List()
    )

    prog.getEvaluator.eval(FunctionInvocation(main, Seq(), Seq())) match {
      case EvaluationResults.Successful(e) => println(e);e
    }

Run and you get:

    "Winner:Winner:"

instead of

    "Winner:Mikael"

**Comment by MikaelMayer** [comment]
I can reproduce that with the latest maven version 1.0.2

**Comment by samarion** [comment]
Fixed in 551222bb4ab028611d4a5d152aa34287f778f7a4
