### ISSUE TITLE
Using Inox in my own project

### ISSUE THREAD

**Issue by ptitjes** [epfl-lara/inox#3]
After having `sbt package publish-local` Inox, I naively add the following line to my build.sbt:
```
libraryDependencies += "ch.epfl.lara" %% "inox" % "1.0"
```

sbt then complains that `princess#princess_2.11;2016-07-01`` is unavailable.

Shouldn't Inox install its hand-managed dependencies ?
Is there an easy way to publish the hand-managed dependencies locally ?

**Comment by samarion** [comment]
Hmm, maybe if you add `aggregate(scalaSmtlib, princess)` to the root project in inox/build.sbt and then publish? I typically use a RootProject with either the path on the file-system to Inox or have it point to the github repo (see https://github.com/epfl-lara/stainless/blob/master/build.sbt). I'll take a look at how this should work with publishing.

**Comment by ptitjes** [comment]
Yes, replacing
```
  .dependsOn(scalaSmtlib)
  .dependsOn(princess)
```
by
```
  .dependsOn(scalaSmtlib)
  .dependsOn(princess)
  .aggregate(scalaSmtlib, princess)
```
did the trick !
Thanks !

As for using `RootProject`, that may be what trips IDEA ( #4 ). Indeed, it sees three project modules that it calls 'root'.

**Comment by samarion** [comment]
`sbt publish-local` will now give you a valid jar. Should also solve https://github.com/epfl-lara/inox/issues/4.

**Comment by ptitjes** [comment]
Sorry for the late answer. I can confirm this now works as expected. Thank you very much !
