### ISSUE TITLE
Check behaviour of model with choose

### ISSUE THREAD

**Issue by mantognini** [epfl-lara/inox#30]
This warning should be fixed and tests added to ensure the feature is acting as expected.
```
[warn] inox/src/main/scala/inox/solvers/unrolling/UnrollingSolver.scala:880: comparing values of types (inox.ast.Identifier, Seq[ModelWrapper.this.model.program.trees.Type]) and inox.ast.Identifier using `==' will always yield false
[warn]     def getChoose(id: Identifier): Option[t.Expr] = model.chooses.find(_._1 == id).map(_._2)
```

[See here.](https://github.com/epfl-lara/inox/commit/cb3b32c8183f38334157876bf6c70f4f4b339793#commitcomment-23072561)

**Comment by samarion** [comment]
Fixed in 09b37f648089df39dd4187c681d040bdfe801c68 and checked during debugging of the issue discussed there.
