### ISSUE TITLE
Fails importing project as sbt project in Intellij IDEA 

### ISSUE THREAD

**Issue by ptitjes** [epfl-lara/inox#4]
It fails without any error. Something strange is that it sees three modules and their corresponding build modules. And then I just don't have any source directory.

**Comment by samarion** [comment]
I can't help there, but I think @manoskouk has it working in Intellij, maybe he can give you some pointers.

**Comment by samarion** [comment]
Inox now only uses libraryDependencies in the build definition, so this shouldn't be an issue anymore.
I don't have Intellij, so please check and close if the issue has indeed been solved.

**Comment by ptitjes** [comment]
I can confirm this now works as expected. Thank you very much !
