### ISSUE TITLE
`--timeout` not respected

### ISSUE THREAD

**Issue by c-cube** [epfl-lara/inox#5]
`inox foo.smt2 --timeout=30` can happily run for dozens of minutes, where `foo.smt2` is a TIP problem.

**Comment by samarion** [comment]
The timeout option tries to leave the solver in some meaningful state (where the computation could be recovered) and this can take a lot of time in some cases. I guess this doesn't really make much sense for a timeout, I'll see about updating the behavior.

**Comment by c-cube** [comment]
Thanks! I've been trying `inox` on a few benchmarks and it takes time :-)

**Comment by samarion** [comment]
Should be fixed in https://github.com/epfl-lara/inox/commit/512a9c554511ea2366132ccda625fe86a1a0d8ae
