### ISSUE TITLE
Allow overriding `SymbolTransformer.transform(FunDef)` & co?

### ISSUE THREAD

**Issue by romac** [epfl-lara/inox#67]
Is there any particular reason why [`SymbolTransformer.transform(FunDef)`](https://github.com/epfl-lara/inox/blob/master/src/main/scala/inox/ast/TreeOps.scala#L229) and [`SymbolTransformer.transform(ADTSort)`](https://github.com/epfl-lara/inox/blob/master/src/main/scala/inox/ast/TreeOps.scala#L240) are marked `final`?

It would be nice to be able to override them when defining a new transformer instead of having to define a custom `def transformFunction(FunDef)` function within the transformer.

**Comment by samarion** [comment]
It's mainly to avoid people redefining them the wrong way, but if you have a valid use case, we can make them overridable.

**Comment by romac** [comment]
Well to me it's mainly cosmetics, so probably not worth changing over that, though it feels a bit arbitrary to have only these two methods as `final`, especially given that one can always rely on `super.transform` to ensure that the transformation is performed the right way.
