### ISSUE TITLE
Model for abstract functions

### ISSUE THREAD

**Issue by c-cube** [epfl-lara/inox#9]
I might have missed something in `inox --help`, but is there an option to print the model when the solver states "SAT"?

**Comment by samarion** [comment]
Inox will assume `(define-fun ...)` to define some interpreted function so it'll ignore it when reporting models. You can use `(define-const ...)` and then rely on the constant in your assertions (I seem to have a bug with global variables that aren't referred to in assertions for now, I'll ping this issue once it's fixed).

**Comment by c-cube** [comment]
I meant displaying the value of undefined constants such as `(declare-fun foo () bar)`

**Comment by samarion** [comment]
Ah yes I meant replace `(declare-fun ...)` by `(declare-const ...)`, sorry.

**Comment by c-cube** [comment]
Hmm, is `declare-const` valid TIP?

**Comment by samarion** [comment]
Well it's in the BNF at https://tip-org.github.io/bnf.html

**Comment by c-cube** [comment]
Indeed, I even parse it. The only issue in my specific case is that most of my constants are introduced in the goal, as in `(assert-not (forall ((x a) (y b)) …)`, but that's ok I guess.

**Comment by samarion** [comment]
I'm going to hijack this issue to remember to output models for abstract functions (`declare-fun`) at some point.

**Comment by samarion** [comment]
Fixed in 51a3a34178d528750c0dfb36470a996eb329a054
