### ISSUE TITLE
Error with default parameters in require

### ISSUE THREAD

**Issue by redelmann** [epfl-lara/inox#94]
The following program:

```scala
package object exError {
  def foo(x: Boolean=true): Boolean = x

  def bar(): Unit = {
    require(foo())

    ()
  }
}
```

Yields the following error:
```
[ Error  ] bar$0 depends on missing dependencies: foo$default$1$0.
[Internal] Missing some nodes in Registry: foo$default$1$0
[Internal] Please inform the authors of Inox about this message
```

**Comment by romac** [comment]
I think this is a problem with Stainless, contrary to what the error message says (which we should fix by the way). I have moved the issue to https://github.com/epfl-lara/stainless/issues/462.

**Comment by samarion** [comment]
Closing since the corresponding Stainless issue has been closed.
